#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin

runlevel=S
prevlevel=N

umask 022

export PATH runlevel prevlevel

mount -a

mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

/usr/sbin/telnetd

mkdir /mnt/rd0
mkdir /mnt/rd1
mkdir /mnt/rd2
mkdir /mnt/rd3
/sbin/mke2fs -q -m 0 /dev/ram0
/bin/mount /dev/ram0 /mnt/rd0
/bin/chown van:root /mnt/rd0
/bin/chmod 0750 /mnt/rd0

/sbin/mke2fs -q -m 0 /dev/ram1
/bin/mount /dev/ram1 /mnt/rd1
/bin/chown van:root /mnt/rd1
/bin/chmod 0750 /mnt/rd1

/sbin/mke2fs -q -m 0 /dev/ram2
/bin/mount /dev/ram2 /mnt/rd2
/bin/chown van:root /mnt/rd2
/bin/chmod 0750 /mnt/rd2

/sbin/mke2fs -q -m 0 /dev/ram3
/bin/mount /dev/ram3 /mnt/rd3
/bin/chown van:root /mnt/rd3
/bin/chmod 0750 /mnt/rd3

#/sbin/ifconfig lo 127.0.0.1
#/sbin/ifconfig eth1 192.168.19.230
#/sbin/ifconfig eth0 192.168.1.230
insmod /usr/local/lib/key.ko
insmod /usr/local/lib/lcd.ko
insmod /usr/local/lib/spi.ko

/usr/local/bin/main &







